### PR TITLE
feat: Add vimfiles.svg

### PR DESCRIPTION
**Pull request by eggbean**
Add vim folder icon for vimfiles. Vim the popular text editor commonly uses a folder in the home directory for its settings, called vimfiles.

### CODE REVIEW

**Comment by eggbean** [comment]
I seem to have got the canvas size wrong, but I am not sure how to correct it in Adobe Illustrator. I didn't think it mattered with vector files? Could somebody show me how to do it or edit the file themselves?

**Comment by nouvist** [comment]
I couldn't see your PR, it says it is error.

**Comment by eggbean** [comment]
It's an .svg file that works fine in Adobe Illustrator, but I didn't know how to set the artboard size, so I think it's too big for displaying in github :/

**Comment by just-a-hriday** [comment]
I fixed this for you, but I noticed that it contains an embedded PNG - I don't think that's allowed here.

**Comment by eggbean** [comment]
Where is your edited file? I can't remember what I did. Was it the vim logo which was the png? There are lots of svg files of the vim logo. If I can get your fixed file I could change it to an svg. I didn't know how to set the artboard in Illustrator.

**Comment by just-a-hriday** [comment]
> Where is your edited file? I can't remember what I did. Was it the vim logo which was the png? There are lots of svg files of the vim logo. If I can get your fixed file I could change it to an svg. I didn't know how to set the artboard in Illustrator.

Yeah, the vim logo was the png. Here's the fixed file! I don't know about yours, but my browser doesn't display the vim logo cause it doesn't like embedded bitmaps.

---

**Comment by eggbean** [comment]
Thanks, I'll add a svg logo some time soon. Could I ask how you fixed it? It would be good to know for next time I attempt making an icon.

**Comment by just-a-hriday** [comment]
> Thanks, I'll add a svg logo some time soon. Could I ask how you fixed it? It would be good to know for next time I attempt making an icon.
> 
> (The logo isn't appearing for me either, on Chrome or Firefox)

The only problem was that Ai hadn't added the xml encoding tag at the beginning of the file.
It was some weird kind of encoding and since I didn't know what it was, I couldn't see the raw xml.
I basically fixed it by opening the file with Inkscape and saving it.

**Pull request closed without merging**
